package db

type ServedThingType string

const (
	StaticFiles ServedThingType = "StaticFiles"
	Alias       ServedThingType = "Alias"

	// not implemented yet
	DockerContainer ServedThingType = "DockerContainer"
	// low-level deployment type; currently just used to expose the admin api
	ReverseProxy ServedThingType = "ReverseProxy"
)

type ExternalSourceType string

const (
	Github ExternalSourceType = "Github"
)

type ExternalUser struct {
	ExternalId      string `storm:"id"`
	ExternalSource  ExternalSourceType
	FullPermissions bool
	// TODO: implement granular permissions, like this:
	// deploymentsTheyHaveAccessTo []string
}

type BearerToken struct {
	Id string `storm:"id"`
	// generated by bcrypt - includes built-in salt
	TokenHash       []byte
	FullPermissions bool
	// TODO: implement granular permissions, like this:
	// deploymentsTheyHaveAccessTo []string
}

type DeploymentMetadata struct {
	Url Url `storm:"id"`

	// for github repos, the ExternalSource has the format "repoOwner/repoName"
	// or "repoOwner/repoName#branch-name"
	ExternalSource     string
	ExternalSourceType ExternalSourceType

	Tags []string

	// if this is true and the deployment is at the path "/thing", then the
	// "/thing" in the path will be transparently passed through to the
	// underlying resource instead of being removed (which is the default)
	PreserveExternalPath bool

	// this is `true` for internal deployments like the one for the admin API.
	// TODO: rename to "internal" because it probably shouldn't be in the API either
	DontPersist bool
}

type DeploymentContent struct {
	// this is false if no actual content has been added to the deployment
	// (yet). (does this even need to exist? why not just use len(ServedThing)
	// > 0, or build in a "NotSureYet" value for ServedThingType?)
	HasContent bool
	// for static files, this is the path to a local directory; for a docker
	// container, this is a port number (?); for a redirect, this is a url or url
	// path; for a reverse proxy, this is a host and port (probably "localhost:[port]")
	ServedThing     string
	ServedThingType ServedThingType

	// this only makes sense for static site content and needs to be moved to a
	// separate type for that content:
	SpaMode bool

	// these only makes sense for aliases:
	AliasedTo Url
	Redirect  bool
}

type Deployment struct {
	DeploymentMetadata `storm:"inline"`
	DeploymentContent  `storm:"inline"`
}

type Url struct {
	Domain string `json:"domain"`
	Path   string `json:"path,omitempty"`
}

func (u *Url) Equals(v *Url) bool {
	return u.Domain == v.Domain && u.Path == v.Path
}

func (u Url) String() string {
	return u.Domain + u.Path
}
