# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/refs/tags/v2.5.0/configuration-schema.json
package: main
generate:
  # specifying just these to avoid generating server code
  client: true
  models: true
output: "sdk.gen.go"
