/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
)

// checks if the GetDeployments200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeployments200Response{}

// GetDeployments200Response struct for GetDeployments200Response
type GetDeployments200Response struct {
	Deployments []GetDeployment200Response `json:"deployments,omitempty"`
}

// NewGetDeployments200Response instantiates a new GetDeployments200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeployments200Response() *GetDeployments200Response {
	this := GetDeployments200Response{}
	return &this
}

// NewGetDeployments200ResponseWithDefaults instantiates a new GetDeployments200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeployments200ResponseWithDefaults() *GetDeployments200Response {
	this := GetDeployments200Response{}
	return &this
}

// GetDeployments returns the Deployments field value if set, zero value otherwise.
func (o *GetDeployments200Response) GetDeployments() []GetDeployment200Response {
	if o == nil || IsNil(o.Deployments) {
		var ret []GetDeployment200Response
		return ret
	}
	return o.Deployments
}

// GetDeploymentsOk returns a tuple with the Deployments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeployments200Response) GetDeploymentsOk() ([]GetDeployment200Response, bool) {
	if o == nil || IsNil(o.Deployments) {
		return nil, false
	}
	return o.Deployments, true
}

// HasDeployments returns a boolean if a field has been set.
func (o *GetDeployments200Response) HasDeployments() bool {
	if o != nil && !IsNil(o.Deployments) {
		return true
	}

	return false
}

// SetDeployments gets a reference to the given []GetDeployment200Response and assigns it to the Deployments field.
func (o *GetDeployments200Response) SetDeployments(v []GetDeployment200Response) {
	o.Deployments = v
}

func (o GetDeployments200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeployments200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deployments) {
		toSerialize["deployments"] = o.Deployments
	}
	return toSerialize, nil
}

type NullableGetDeployments200Response struct {
	value *GetDeployments200Response
	isSet bool
}

func (v NullableGetDeployments200Response) Get() *GetDeployments200Response {
	return v.value
}

func (v *NullableGetDeployments200Response) Set(val *GetDeployments200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeployments200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeployments200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeployments200Response(val *GetDeployments200Response) *NullableGetDeployments200Response {
	return &NullableGetDeployments200Response{value: val, isSet: true}
}

func (v NullableGetDeployments200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeployments200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


