/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SiteMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMeta{}

// SiteMeta struct for SiteMeta
type SiteMeta struct {
	Description string `json:"description"`
	Image string `json:"image"`
	Title string `json:"title"`
}

type _SiteMeta SiteMeta

// NewSiteMeta instantiates a new SiteMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMeta(description string, image string, title string) *SiteMeta {
	this := SiteMeta{}
	this.Description = description
	this.Image = image
	this.Title = title
	return &this
}

// NewSiteMetaWithDefaults instantiates a new SiteMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMetaWithDefaults() *SiteMeta {
	this := SiteMeta{}
	return &this
}

// GetDescription returns the Description field value
func (o *SiteMeta) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SiteMeta) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SiteMeta) SetDescription(v string) {
	o.Description = v
}

// GetImage returns the Image field value
func (o *SiteMeta) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *SiteMeta) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *SiteMeta) SetImage(v string) {
	o.Image = v
}

// GetTitle returns the Title field value
func (o *SiteMeta) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *SiteMeta) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *SiteMeta) SetTitle(v string) {
	o.Title = v
}

func (o SiteMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["image"] = o.Image
	toSerialize["title"] = o.Title
	return toSerialize, nil
}

func (o *SiteMeta) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"image",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSiteMeta := _SiteMeta{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSiteMeta)

	if err != nil {
		return err
	}

	*o = SiteMeta(varSiteMeta)

	return err
}

type NullableSiteMeta struct {
	value *SiteMeta
	isSet bool
}

func (v NullableSiteMeta) Get() *SiteMeta {
	return v.value
}

func (v *NullableSiteMeta) Set(val *SiteMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMeta(val *SiteMeta) *NullableSiteMeta {
	return &NullableSiteMeta{value: val, isSet: true}
}

func (v NullableSiteMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


