/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GetDeploymentsOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeploymentsOutputBody{}

// GetDeploymentsOutputBody struct for GetDeploymentsOutputBody
type GetDeploymentsOutputBody struct {
	Deployments []DeploymentModel `json:"deployments"`
	AdditionalProperties map[string]interface{}
}

type _GetDeploymentsOutputBody GetDeploymentsOutputBody

// NewGetDeploymentsOutputBody instantiates a new GetDeploymentsOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeploymentsOutputBody(deployments []DeploymentModel) *GetDeploymentsOutputBody {
	this := GetDeploymentsOutputBody{}
	this.Deployments = deployments
	return &this
}

// NewGetDeploymentsOutputBodyWithDefaults instantiates a new GetDeploymentsOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeploymentsOutputBodyWithDefaults() *GetDeploymentsOutputBody {
	this := GetDeploymentsOutputBody{}
	return &this
}

// GetDeployments returns the Deployments field value
// If the value is explicit nil, the zero value for []DeploymentModel will be returned
func (o *GetDeploymentsOutputBody) GetDeployments() []DeploymentModel {
	if o == nil {
		var ret []DeploymentModel
		return ret
	}

	return o.Deployments
}

// GetDeploymentsOk returns a tuple with the Deployments field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDeploymentsOutputBody) GetDeploymentsOk() ([]DeploymentModel, bool) {
	if o == nil || IsNil(o.Deployments) {
		return nil, false
	}
	return o.Deployments, true
}

// SetDeployments sets field value
func (o *GetDeploymentsOutputBody) SetDeployments(v []DeploymentModel) {
	o.Deployments = v
}

func (o GetDeploymentsOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeploymentsOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Deployments != nil {
		toSerialize["deployments"] = o.Deployments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetDeploymentsOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deployments",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDeploymentsOutputBody := _GetDeploymentsOutputBody{}

	err = json.Unmarshal(data, &varGetDeploymentsOutputBody)

	if err != nil {
		return err
	}

	*o = GetDeploymentsOutputBody(varGetDeploymentsOutputBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "deployments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetDeploymentsOutputBody struct {
	value *GetDeploymentsOutputBody
	isSet bool
}

func (v NullableGetDeploymentsOutputBody) Get() *GetDeploymentsOutputBody {
	return v.value
}

func (v *NullableGetDeploymentsOutputBody) Set(val *GetDeploymentsOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeploymentsOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeploymentsOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeploymentsOutputBody(val *GetDeploymentsOutputBody) *NullableGetDeploymentsOutputBody {
	return &NullableGetDeploymentsOutputBody{value: val, isSet: true}
}

func (v NullableGetDeploymentsOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeploymentsOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


