/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeployAdminDashBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeployAdminDashBody{}

// DeployAdminDashBody struct for DeployAdminDashBody
type DeployAdminDashBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Url string `json:"url"`
}

type _DeployAdminDashBody DeployAdminDashBody

// NewDeployAdminDashBody instantiates a new DeployAdminDashBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeployAdminDashBody(url string) *DeployAdminDashBody {
	this := DeployAdminDashBody{}
	this.Url = url
	return &this
}

// NewDeployAdminDashBodyWithDefaults instantiates a new DeployAdminDashBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeployAdminDashBodyWithDefaults() *DeployAdminDashBody {
	this := DeployAdminDashBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *DeployAdminDashBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAdminDashBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *DeployAdminDashBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *DeployAdminDashBody) SetSchema(v string) {
	o.Schema = &v
}

// GetUrl returns the Url field value
func (o *DeployAdminDashBody) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *DeployAdminDashBody) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *DeployAdminDashBody) SetUrl(v string) {
	o.Url = v
}

func (o DeployAdminDashBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeployAdminDashBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *DeployAdminDashBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeployAdminDashBody := _DeployAdminDashBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeployAdminDashBody)

	if err != nil {
		return err
	}

	*o = DeployAdminDashBody(varDeployAdminDashBody)

	return err
}

type NullableDeployAdminDashBody struct {
	value *DeployAdminDashBody
	isSet bool
}

func (v NullableDeployAdminDashBody) Get() *DeployAdminDashBody {
	return v.value
}

func (v *NullableDeployAdminDashBody) Set(val *DeployAdminDashBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDeployAdminDashBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDeployAdminDashBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeployAdminDashBody(val *DeployAdminDashBody) *NullableDeployAdminDashBody {
	return &NullableDeployAdminDashBody{value: val, isSet: true}
}

func (v NullableDeployAdminDashBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeployAdminDashBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


