/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AliasDeployment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AliasDeployment{}

// AliasDeployment struct for AliasDeployment
type AliasDeployment struct {
	// The URL that this deployment is an alias for.
	AliasedTo *string `json:"aliasedTo,omitempty"`
	// When the deployment was created (string in ISO-8601 format.)
	CreatedAt string `json:"createdAt"`
	// Original repository for this deployment's source. Can include a branch name.
	ExternalSource *string `json:"externalSource,omitempty"`
	// Place where the original repository lives.
	ExternalSourceType *string `json:"externalSourceType,omitempty"`
	Meta SiteMeta `json:"meta"`
	// Name for the deployment. This is just metadata; make it whatever you want.
	Name string `json:"name"`
	// If this is true and the deployment url has a path like \"/thing\", then the \"/thing\" in the path will be transparently passed through to the underlying resource instead of being removed (which is the default)
	PreserveExternalPath *bool `json:"preserveExternalPath,omitempty"`
	// If this is true, visitors to this deployment's URL will be completely redirected to the URL that this alias is for.
	Redirect *bool `json:"redirect,omitempty"`
	// Tags used for metadata.
	Tags []string `json:"tags,omitempty"`
	// Type of deployment contents.
	Type string `json:"type"`
	// When the deployment was last updated (string in ISO-8601 format.)
	UpdatedAt string `json:"updatedAt"`
	// URL that this deployment will appear at. The DNS for the domain has to be set up first.
	Url string `json:"url"`
}

type _AliasDeployment AliasDeployment

// NewAliasDeployment instantiates a new AliasDeployment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAliasDeployment(createdAt string, meta SiteMeta, name string, type_ string, updatedAt string, url string) *AliasDeployment {
	this := AliasDeployment{}
	this.CreatedAt = createdAt
	this.Meta = meta
	this.Name = name
	this.Type = type_
	this.UpdatedAt = updatedAt
	this.Url = url
	return &this
}

// NewAliasDeploymentWithDefaults instantiates a new AliasDeployment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAliasDeploymentWithDefaults() *AliasDeployment {
	this := AliasDeployment{}
	return &this
}

// GetAliasedTo returns the AliasedTo field value if set, zero value otherwise.
func (o *AliasDeployment) GetAliasedTo() string {
	if o == nil || IsNil(o.AliasedTo) {
		var ret string
		return ret
	}
	return *o.AliasedTo
}

// GetAliasedToOk returns a tuple with the AliasedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetAliasedToOk() (*string, bool) {
	if o == nil || IsNil(o.AliasedTo) {
		return nil, false
	}
	return o.AliasedTo, true
}

// HasAliasedTo returns a boolean if a field has been set.
func (o *AliasDeployment) HasAliasedTo() bool {
	if o != nil && !IsNil(o.AliasedTo) {
		return true
	}

	return false
}

// SetAliasedTo gets a reference to the given string and assigns it to the AliasedTo field.
func (o *AliasDeployment) SetAliasedTo(v string) {
	o.AliasedTo = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AliasDeployment) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AliasDeployment) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetExternalSource returns the ExternalSource field value if set, zero value otherwise.
func (o *AliasDeployment) GetExternalSource() string {
	if o == nil || IsNil(o.ExternalSource) {
		var ret string
		return ret
	}
	return *o.ExternalSource
}

// GetExternalSourceOk returns a tuple with the ExternalSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetExternalSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSource) {
		return nil, false
	}
	return o.ExternalSource, true
}

// HasExternalSource returns a boolean if a field has been set.
func (o *AliasDeployment) HasExternalSource() bool {
	if o != nil && !IsNil(o.ExternalSource) {
		return true
	}

	return false
}

// SetExternalSource gets a reference to the given string and assigns it to the ExternalSource field.
func (o *AliasDeployment) SetExternalSource(v string) {
	o.ExternalSource = &v
}

// GetExternalSourceType returns the ExternalSourceType field value if set, zero value otherwise.
func (o *AliasDeployment) GetExternalSourceType() string {
	if o == nil || IsNil(o.ExternalSourceType) {
		var ret string
		return ret
	}
	return *o.ExternalSourceType
}

// GetExternalSourceTypeOk returns a tuple with the ExternalSourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetExternalSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSourceType) {
		return nil, false
	}
	return o.ExternalSourceType, true
}

// HasExternalSourceType returns a boolean if a field has been set.
func (o *AliasDeployment) HasExternalSourceType() bool {
	if o != nil && !IsNil(o.ExternalSourceType) {
		return true
	}

	return false
}

// SetExternalSourceType gets a reference to the given string and assigns it to the ExternalSourceType field.
func (o *AliasDeployment) SetExternalSourceType(v string) {
	o.ExternalSourceType = &v
}

// GetMeta returns the Meta field value
func (o *AliasDeployment) GetMeta() SiteMeta {
	if o == nil {
		var ret SiteMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetMetaOk() (*SiteMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *AliasDeployment) SetMeta(v SiteMeta) {
	o.Meta = v
}

// GetName returns the Name field value
func (o *AliasDeployment) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AliasDeployment) SetName(v string) {
	o.Name = v
}

// GetPreserveExternalPath returns the PreserveExternalPath field value if set, zero value otherwise.
func (o *AliasDeployment) GetPreserveExternalPath() bool {
	if o == nil || IsNil(o.PreserveExternalPath) {
		var ret bool
		return ret
	}
	return *o.PreserveExternalPath
}

// GetPreserveExternalPathOk returns a tuple with the PreserveExternalPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetPreserveExternalPathOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveExternalPath) {
		return nil, false
	}
	return o.PreserveExternalPath, true
}

// HasPreserveExternalPath returns a boolean if a field has been set.
func (o *AliasDeployment) HasPreserveExternalPath() bool {
	if o != nil && !IsNil(o.PreserveExternalPath) {
		return true
	}

	return false
}

// SetPreserveExternalPath gets a reference to the given bool and assigns it to the PreserveExternalPath field.
func (o *AliasDeployment) SetPreserveExternalPath(v bool) {
	o.PreserveExternalPath = &v
}

// GetRedirect returns the Redirect field value if set, zero value otherwise.
func (o *AliasDeployment) GetRedirect() bool {
	if o == nil || IsNil(o.Redirect) {
		var ret bool
		return ret
	}
	return *o.Redirect
}

// GetRedirectOk returns a tuple with the Redirect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetRedirectOk() (*bool, bool) {
	if o == nil || IsNil(o.Redirect) {
		return nil, false
	}
	return o.Redirect, true
}

// HasRedirect returns a boolean if a field has been set.
func (o *AliasDeployment) HasRedirect() bool {
	if o != nil && !IsNil(o.Redirect) {
		return true
	}

	return false
}

// SetRedirect gets a reference to the given bool and assigns it to the Redirect field.
func (o *AliasDeployment) SetRedirect(v bool) {
	o.Redirect = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AliasDeployment) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AliasDeployment) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *AliasDeployment) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *AliasDeployment) SetTags(v []string) {
	o.Tags = v
}

// GetType returns the Type field value
func (o *AliasDeployment) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AliasDeployment) SetType(v string) {
	o.Type = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AliasDeployment) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AliasDeployment) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetUrl returns the Url field value
func (o *AliasDeployment) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *AliasDeployment) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *AliasDeployment) SetUrl(v string) {
	o.Url = v
}

func (o AliasDeployment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AliasDeployment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AliasedTo) {
		toSerialize["aliasedTo"] = o.AliasedTo
	}
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.ExternalSource) {
		toSerialize["externalSource"] = o.ExternalSource
	}
	if !IsNil(o.ExternalSourceType) {
		toSerialize["externalSourceType"] = o.ExternalSourceType
	}
	toSerialize["meta"] = o.Meta
	toSerialize["name"] = o.Name
	if !IsNil(o.PreserveExternalPath) {
		toSerialize["preserveExternalPath"] = o.PreserveExternalPath
	}
	if !IsNil(o.Redirect) {
		toSerialize["redirect"] = o.Redirect
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["type"] = o.Type
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *AliasDeployment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"meta",
		"name",
		"type",
		"updatedAt",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAliasDeployment := _AliasDeployment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAliasDeployment)

	if err != nil {
		return err
	}

	*o = AliasDeployment(varAliasDeployment)

	return err
}

type NullableAliasDeployment struct {
	value *AliasDeployment
	isSet bool
}

func (v NullableAliasDeployment) Get() *AliasDeployment {
	return v.value
}

func (v *NullableAliasDeployment) Set(val *AliasDeployment) {
	v.value = val
	v.isSet = true
}

func (v NullableAliasDeployment) IsSet() bool {
	return v.isSet
}

func (v *NullableAliasDeployment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAliasDeployment(val *AliasDeployment) *NullableAliasDeployment {
	return &NullableAliasDeployment{value: val, isSet: true}
}

func (v NullableAliasDeployment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAliasDeployment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


