/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// GetDeployment200Response - struct for GetDeployment200Response
type GetDeployment200Response struct {
	AliasDeployment *AliasDeployment
	DeploymentBase *DeploymentBase
	StaticSiteDeployment *StaticSiteDeployment
}

// AliasDeploymentAsGetDeployment200Response is a convenience function that returns AliasDeployment wrapped in GetDeployment200Response
func AliasDeploymentAsGetDeployment200Response(v *AliasDeployment) GetDeployment200Response {
	return GetDeployment200Response{
		AliasDeployment: v,
	}
}

// DeploymentBaseAsGetDeployment200Response is a convenience function that returns DeploymentBase wrapped in GetDeployment200Response
func DeploymentBaseAsGetDeployment200Response(v *DeploymentBase) GetDeployment200Response {
	return GetDeployment200Response{
		DeploymentBase: v,
	}
}

// StaticSiteDeploymentAsGetDeployment200Response is a convenience function that returns StaticSiteDeployment wrapped in GetDeployment200Response
func StaticSiteDeploymentAsGetDeployment200Response(v *StaticSiteDeployment) GetDeployment200Response {
	return GetDeployment200Response{
		StaticSiteDeployment: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetDeployment200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AliasDeployment
	err = newStrictDecoder(data).Decode(&dst.AliasDeployment)
	if err == nil {
		jsonAliasDeployment, _ := json.Marshal(dst.AliasDeployment)
		if string(jsonAliasDeployment) == "{}" { // empty struct
			dst.AliasDeployment = nil
		} else {
			if err = validator.Validate(dst.AliasDeployment); err != nil {
				dst.AliasDeployment = nil
			} else {
				match++
			}
		}
	} else {
		dst.AliasDeployment = nil
	}

	// try to unmarshal data into DeploymentBase
	err = newStrictDecoder(data).Decode(&dst.DeploymentBase)
	if err == nil {
		jsonDeploymentBase, _ := json.Marshal(dst.DeploymentBase)
		if string(jsonDeploymentBase) == "{}" { // empty struct
			dst.DeploymentBase = nil
		} else {
			if err = validator.Validate(dst.DeploymentBase); err != nil {
				dst.DeploymentBase = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeploymentBase = nil
	}

	// try to unmarshal data into StaticSiteDeployment
	err = newStrictDecoder(data).Decode(&dst.StaticSiteDeployment)
	if err == nil {
		jsonStaticSiteDeployment, _ := json.Marshal(dst.StaticSiteDeployment)
		if string(jsonStaticSiteDeployment) == "{}" { // empty struct
			dst.StaticSiteDeployment = nil
		} else {
			if err = validator.Validate(dst.StaticSiteDeployment); err != nil {
				dst.StaticSiteDeployment = nil
			} else {
				match++
			}
		}
	} else {
		dst.StaticSiteDeployment = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AliasDeployment = nil
		dst.DeploymentBase = nil
		dst.StaticSiteDeployment = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetDeployment200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetDeployment200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetDeployment200Response) MarshalJSON() ([]byte, error) {
	if src.AliasDeployment != nil {
		return json.Marshal(&src.AliasDeployment)
	}

	if src.DeploymentBase != nil {
		return json.Marshal(&src.DeploymentBase)
	}

	if src.StaticSiteDeployment != nil {
		return json.Marshal(&src.StaticSiteDeployment)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetDeployment200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AliasDeployment != nil {
		return obj.AliasDeployment
	}

	if obj.DeploymentBase != nil {
		return obj.DeploymentBase
	}

	if obj.StaticSiteDeployment != nil {
		return obj.StaticSiteDeployment
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj GetDeployment200Response) GetActualInstanceValue() (interface{}) {
	if obj.AliasDeployment != nil {
		return *obj.AliasDeployment
	}

	if obj.DeploymentBase != nil {
		return *obj.DeploymentBase
	}

	if obj.StaticSiteDeployment != nil {
		return *obj.StaticSiteDeployment
	}

	// all schemas are nil
	return nil
}

type NullableGetDeployment200Response struct {
	value *GetDeployment200Response
	isSet bool
}

func (v NullableGetDeployment200Response) Get() *GetDeployment200Response {
	return v.value
}

func (v *NullableGetDeployment200Response) Set(val *GetDeployment200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeployment200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeployment200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeployment200Response(val *GetDeployment200Response) *NullableGetDeployment200Response {
	return &NullableGetDeployment200Response{value: val, isSet: true}
}

func (v NullableGetDeployment200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeployment200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


