/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the DeploymentResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentResponseBody{}

// DeploymentResponseBody struct for DeploymentResponseBody
type DeploymentResponseBody struct {
	// The URL that this deployment is an alias for.
	AliasedTo *string `json:"aliasedTo,omitempty"`
	// Original repository for this deployment's source. Can include a branch name.
	ExternalSource *string `json:"externalSource,omitempty"`
	// Place where the original repository lives.
	ExternalSourceType *string `json:"externalSourceType,omitempty"`
	// Set to true if this deployment has not yet been set up.
	NoContentYet bool `json:"noContentYet"`
	// if this is true and the deployment url has a path like \"/thing\", then the \"/thing\" in the path will be transparently passed through to the underlying resource instead of being removed (which is the default)
	PreserveExternalPath *bool `json:"preserveExternalPath,omitempty"`
	// If this is true, visitors to this deployment's URL will be completely redirected to the URL that this alias is for.
	Redirect *bool `json:"redirect,omitempty"`
	// The path to this deployment's files on the server.
	ServerContentLocation *string `json:"serverContentLocation,omitempty"`
	// Whether this deployment is set up to support a Single Page App by using /index.html as a fallback for all requests.
	SpaMode *bool `json:"spaMode,omitempty"`
	// Tags used for metadata.
	Tags []string `json:"tags,omitempty"`
	// Type of deployment contents.
	Type string `json:"type"`
	// URL that this deployment will appear at. The DNS for the domain has to be set up first.
	Url string `json:"url"`
	AdditionalProperties map[string]interface{}
}

type _DeploymentResponseBody DeploymentResponseBody

// NewDeploymentResponseBody instantiates a new DeploymentResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentResponseBody(noContentYet bool, type_ string, url string) *DeploymentResponseBody {
	this := DeploymentResponseBody{}
	this.NoContentYet = noContentYet
	this.Type = type_
	this.Url = url
	return &this
}

// NewDeploymentResponseBodyWithDefaults instantiates a new DeploymentResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentResponseBodyWithDefaults() *DeploymentResponseBody {
	this := DeploymentResponseBody{}
	return &this
}

// GetAliasedTo returns the AliasedTo field value if set, zero value otherwise.
func (o *DeploymentResponseBody) GetAliasedTo() string {
	if o == nil || IsNil(o.AliasedTo) {
		var ret string
		return ret
	}
	return *o.AliasedTo
}

// GetAliasedToOk returns a tuple with the AliasedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentResponseBody) GetAliasedToOk() (*string, bool) {
	if o == nil || IsNil(o.AliasedTo) {
		return nil, false
	}
	return o.AliasedTo, true
}

// HasAliasedTo returns a boolean if a field has been set.
func (o *DeploymentResponseBody) HasAliasedTo() bool {
	if o != nil && !IsNil(o.AliasedTo) {
		return true
	}

	return false
}

// SetAliasedTo gets a reference to the given string and assigns it to the AliasedTo field.
func (o *DeploymentResponseBody) SetAliasedTo(v string) {
	o.AliasedTo = &v
}

// GetExternalSource returns the ExternalSource field value if set, zero value otherwise.
func (o *DeploymentResponseBody) GetExternalSource() string {
	if o == nil || IsNil(o.ExternalSource) {
		var ret string
		return ret
	}
	return *o.ExternalSource
}

// GetExternalSourceOk returns a tuple with the ExternalSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentResponseBody) GetExternalSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSource) {
		return nil, false
	}
	return o.ExternalSource, true
}

// HasExternalSource returns a boolean if a field has been set.
func (o *DeploymentResponseBody) HasExternalSource() bool {
	if o != nil && !IsNil(o.ExternalSource) {
		return true
	}

	return false
}

// SetExternalSource gets a reference to the given string and assigns it to the ExternalSource field.
func (o *DeploymentResponseBody) SetExternalSource(v string) {
	o.ExternalSource = &v
}

// GetExternalSourceType returns the ExternalSourceType field value if set, zero value otherwise.
func (o *DeploymentResponseBody) GetExternalSourceType() string {
	if o == nil || IsNil(o.ExternalSourceType) {
		var ret string
		return ret
	}
	return *o.ExternalSourceType
}

// GetExternalSourceTypeOk returns a tuple with the ExternalSourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentResponseBody) GetExternalSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSourceType) {
		return nil, false
	}
	return o.ExternalSourceType, true
}

// HasExternalSourceType returns a boolean if a field has been set.
func (o *DeploymentResponseBody) HasExternalSourceType() bool {
	if o != nil && !IsNil(o.ExternalSourceType) {
		return true
	}

	return false
}

// SetExternalSourceType gets a reference to the given string and assigns it to the ExternalSourceType field.
func (o *DeploymentResponseBody) SetExternalSourceType(v string) {
	o.ExternalSourceType = &v
}

// GetNoContentYet returns the NoContentYet field value
func (o *DeploymentResponseBody) GetNoContentYet() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.NoContentYet
}

// GetNoContentYetOk returns a tuple with the NoContentYet field value
// and a boolean to check if the value has been set.
func (o *DeploymentResponseBody) GetNoContentYetOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NoContentYet, true
}

// SetNoContentYet sets field value
func (o *DeploymentResponseBody) SetNoContentYet(v bool) {
	o.NoContentYet = v
}

// GetPreserveExternalPath returns the PreserveExternalPath field value if set, zero value otherwise.
func (o *DeploymentResponseBody) GetPreserveExternalPath() bool {
	if o == nil || IsNil(o.PreserveExternalPath) {
		var ret bool
		return ret
	}
	return *o.PreserveExternalPath
}

// GetPreserveExternalPathOk returns a tuple with the PreserveExternalPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentResponseBody) GetPreserveExternalPathOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveExternalPath) {
		return nil, false
	}
	return o.PreserveExternalPath, true
}

// HasPreserveExternalPath returns a boolean if a field has been set.
func (o *DeploymentResponseBody) HasPreserveExternalPath() bool {
	if o != nil && !IsNil(o.PreserveExternalPath) {
		return true
	}

	return false
}

// SetPreserveExternalPath gets a reference to the given bool and assigns it to the PreserveExternalPath field.
func (o *DeploymentResponseBody) SetPreserveExternalPath(v bool) {
	o.PreserveExternalPath = &v
}

// GetRedirect returns the Redirect field value if set, zero value otherwise.
func (o *DeploymentResponseBody) GetRedirect() bool {
	if o == nil || IsNil(o.Redirect) {
		var ret bool
		return ret
	}
	return *o.Redirect
}

// GetRedirectOk returns a tuple with the Redirect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentResponseBody) GetRedirectOk() (*bool, bool) {
	if o == nil || IsNil(o.Redirect) {
		return nil, false
	}
	return o.Redirect, true
}

// HasRedirect returns a boolean if a field has been set.
func (o *DeploymentResponseBody) HasRedirect() bool {
	if o != nil && !IsNil(o.Redirect) {
		return true
	}

	return false
}

// SetRedirect gets a reference to the given bool and assigns it to the Redirect field.
func (o *DeploymentResponseBody) SetRedirect(v bool) {
	o.Redirect = &v
}

// GetServerContentLocation returns the ServerContentLocation field value if set, zero value otherwise.
func (o *DeploymentResponseBody) GetServerContentLocation() string {
	if o == nil || IsNil(o.ServerContentLocation) {
		var ret string
		return ret
	}
	return *o.ServerContentLocation
}

// GetServerContentLocationOk returns a tuple with the ServerContentLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentResponseBody) GetServerContentLocationOk() (*string, bool) {
	if o == nil || IsNil(o.ServerContentLocation) {
		return nil, false
	}
	return o.ServerContentLocation, true
}

// HasServerContentLocation returns a boolean if a field has been set.
func (o *DeploymentResponseBody) HasServerContentLocation() bool {
	if o != nil && !IsNil(o.ServerContentLocation) {
		return true
	}

	return false
}

// SetServerContentLocation gets a reference to the given string and assigns it to the ServerContentLocation field.
func (o *DeploymentResponseBody) SetServerContentLocation(v string) {
	o.ServerContentLocation = &v
}

// GetSpaMode returns the SpaMode field value if set, zero value otherwise.
func (o *DeploymentResponseBody) GetSpaMode() bool {
	if o == nil || IsNil(o.SpaMode) {
		var ret bool
		return ret
	}
	return *o.SpaMode
}

// GetSpaModeOk returns a tuple with the SpaMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentResponseBody) GetSpaModeOk() (*bool, bool) {
	if o == nil || IsNil(o.SpaMode) {
		return nil, false
	}
	return o.SpaMode, true
}

// HasSpaMode returns a boolean if a field has been set.
func (o *DeploymentResponseBody) HasSpaMode() bool {
	if o != nil && !IsNil(o.SpaMode) {
		return true
	}

	return false
}

// SetSpaMode gets a reference to the given bool and assigns it to the SpaMode field.
func (o *DeploymentResponseBody) SetSpaMode(v bool) {
	o.SpaMode = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeploymentResponseBody) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentResponseBody) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *DeploymentResponseBody) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *DeploymentResponseBody) SetTags(v []string) {
	o.Tags = v
}

// GetType returns the Type field value
func (o *DeploymentResponseBody) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DeploymentResponseBody) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DeploymentResponseBody) SetType(v string) {
	o.Type = v
}

// GetUrl returns the Url field value
func (o *DeploymentResponseBody) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *DeploymentResponseBody) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *DeploymentResponseBody) SetUrl(v string) {
	o.Url = v
}

func (o DeploymentResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AliasedTo) {
		toSerialize["aliasedTo"] = o.AliasedTo
	}
	if !IsNil(o.ExternalSource) {
		toSerialize["externalSource"] = o.ExternalSource
	}
	if !IsNil(o.ExternalSourceType) {
		toSerialize["externalSourceType"] = o.ExternalSourceType
	}
	toSerialize["noContentYet"] = o.NoContentYet
	if !IsNil(o.PreserveExternalPath) {
		toSerialize["preserveExternalPath"] = o.PreserveExternalPath
	}
	if !IsNil(o.Redirect) {
		toSerialize["redirect"] = o.Redirect
	}
	if !IsNil(o.ServerContentLocation) {
		toSerialize["serverContentLocation"] = o.ServerContentLocation
	}
	if !IsNil(o.SpaMode) {
		toSerialize["spaMode"] = o.SpaMode
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["type"] = o.Type
	toSerialize["url"] = o.Url

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeploymentResponseBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"noContentYet",
		"type",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentResponseBody := _DeploymentResponseBody{}

	err = json.Unmarshal(data, &varDeploymentResponseBody)

	if err != nil {
		return err
	}

	*o = DeploymentResponseBody(varDeploymentResponseBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "aliasedTo")
		delete(additionalProperties, "externalSource")
		delete(additionalProperties, "externalSourceType")
		delete(additionalProperties, "noContentYet")
		delete(additionalProperties, "preserveExternalPath")
		delete(additionalProperties, "redirect")
		delete(additionalProperties, "serverContentLocation")
		delete(additionalProperties, "spaMode")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "type")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeploymentResponseBody struct {
	value *DeploymentResponseBody
	isSet bool
}

func (v NullableDeploymentResponseBody) Get() *DeploymentResponseBody {
	return v.value
}

func (v *NullableDeploymentResponseBody) Set(val *DeploymentResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentResponseBody(val *DeploymentResponseBody) *NullableDeploymentResponseBody {
	return &NullableDeploymentResponseBody{value: val, isSet: true}
}

func (v NullableDeploymentResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


