/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseIfAlias type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseIfAlias{}

// ResponseIfAlias struct for ResponseIfAlias
type ResponseIfAlias struct {
	// The URL that this deployment is an alias for.
	AliasedTo *string `json:"aliasedTo,omitempty"`
	// Original repository for this deployment's source. Can include a branch name.
	ExternalSource *string `json:"externalSource,omitempty"`
	// Place where the original repository lives.
	ExternalSourceType *string `json:"externalSourceType,omitempty"`
	// if this is true and the deployment url has a path like \"/thing\", then the \"/thing\" in the path will be transparently passed through to the underlying resource instead of being removed (which is the default)
	PreserveExternalPath *bool `json:"preserveExternalPath,omitempty"`
	// If this is true, visitors to this deployment's URL will be completely redirected to the URL that this alias is for.
	Redirect *bool `json:"redirect,omitempty"`
	// Tags used for metadata.
	Tags []string `json:"tags,omitempty"`
	// Type of deployment contents.
	Type string `json:"type"`
	// URL that this deployment will appear at. The DNS for the domain has to be set up first.
	Url string `json:"url"`
}

type _ResponseIfAlias ResponseIfAlias

// NewResponseIfAlias instantiates a new ResponseIfAlias object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseIfAlias(type_ string, url string) *ResponseIfAlias {
	this := ResponseIfAlias{}
	this.Type = type_
	this.Url = url
	return &this
}

// NewResponseIfAliasWithDefaults instantiates a new ResponseIfAlias object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseIfAliasWithDefaults() *ResponseIfAlias {
	this := ResponseIfAlias{}
	return &this
}

// GetAliasedTo returns the AliasedTo field value if set, zero value otherwise.
func (o *ResponseIfAlias) GetAliasedTo() string {
	if o == nil || IsNil(o.AliasedTo) {
		var ret string
		return ret
	}
	return *o.AliasedTo
}

// GetAliasedToOk returns a tuple with the AliasedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIfAlias) GetAliasedToOk() (*string, bool) {
	if o == nil || IsNil(o.AliasedTo) {
		return nil, false
	}
	return o.AliasedTo, true
}

// HasAliasedTo returns a boolean if a field has been set.
func (o *ResponseIfAlias) HasAliasedTo() bool {
	if o != nil && !IsNil(o.AliasedTo) {
		return true
	}

	return false
}

// SetAliasedTo gets a reference to the given string and assigns it to the AliasedTo field.
func (o *ResponseIfAlias) SetAliasedTo(v string) {
	o.AliasedTo = &v
}

// GetExternalSource returns the ExternalSource field value if set, zero value otherwise.
func (o *ResponseIfAlias) GetExternalSource() string {
	if o == nil || IsNil(o.ExternalSource) {
		var ret string
		return ret
	}
	return *o.ExternalSource
}

// GetExternalSourceOk returns a tuple with the ExternalSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIfAlias) GetExternalSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSource) {
		return nil, false
	}
	return o.ExternalSource, true
}

// HasExternalSource returns a boolean if a field has been set.
func (o *ResponseIfAlias) HasExternalSource() bool {
	if o != nil && !IsNil(o.ExternalSource) {
		return true
	}

	return false
}

// SetExternalSource gets a reference to the given string and assigns it to the ExternalSource field.
func (o *ResponseIfAlias) SetExternalSource(v string) {
	o.ExternalSource = &v
}

// GetExternalSourceType returns the ExternalSourceType field value if set, zero value otherwise.
func (o *ResponseIfAlias) GetExternalSourceType() string {
	if o == nil || IsNil(o.ExternalSourceType) {
		var ret string
		return ret
	}
	return *o.ExternalSourceType
}

// GetExternalSourceTypeOk returns a tuple with the ExternalSourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIfAlias) GetExternalSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSourceType) {
		return nil, false
	}
	return o.ExternalSourceType, true
}

// HasExternalSourceType returns a boolean if a field has been set.
func (o *ResponseIfAlias) HasExternalSourceType() bool {
	if o != nil && !IsNil(o.ExternalSourceType) {
		return true
	}

	return false
}

// SetExternalSourceType gets a reference to the given string and assigns it to the ExternalSourceType field.
func (o *ResponseIfAlias) SetExternalSourceType(v string) {
	o.ExternalSourceType = &v
}

// GetPreserveExternalPath returns the PreserveExternalPath field value if set, zero value otherwise.
func (o *ResponseIfAlias) GetPreserveExternalPath() bool {
	if o == nil || IsNil(o.PreserveExternalPath) {
		var ret bool
		return ret
	}
	return *o.PreserveExternalPath
}

// GetPreserveExternalPathOk returns a tuple with the PreserveExternalPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIfAlias) GetPreserveExternalPathOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveExternalPath) {
		return nil, false
	}
	return o.PreserveExternalPath, true
}

// HasPreserveExternalPath returns a boolean if a field has been set.
func (o *ResponseIfAlias) HasPreserveExternalPath() bool {
	if o != nil && !IsNil(o.PreserveExternalPath) {
		return true
	}

	return false
}

// SetPreserveExternalPath gets a reference to the given bool and assigns it to the PreserveExternalPath field.
func (o *ResponseIfAlias) SetPreserveExternalPath(v bool) {
	o.PreserveExternalPath = &v
}

// GetRedirect returns the Redirect field value if set, zero value otherwise.
func (o *ResponseIfAlias) GetRedirect() bool {
	if o == nil || IsNil(o.Redirect) {
		var ret bool
		return ret
	}
	return *o.Redirect
}

// GetRedirectOk returns a tuple with the Redirect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIfAlias) GetRedirectOk() (*bool, bool) {
	if o == nil || IsNil(o.Redirect) {
		return nil, false
	}
	return o.Redirect, true
}

// HasRedirect returns a boolean if a field has been set.
func (o *ResponseIfAlias) HasRedirect() bool {
	if o != nil && !IsNil(o.Redirect) {
		return true
	}

	return false
}

// SetRedirect gets a reference to the given bool and assigns it to the Redirect field.
func (o *ResponseIfAlias) SetRedirect(v bool) {
	o.Redirect = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseIfAlias) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseIfAlias) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ResponseIfAlias) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *ResponseIfAlias) SetTags(v []string) {
	o.Tags = v
}

// GetType returns the Type field value
func (o *ResponseIfAlias) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ResponseIfAlias) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ResponseIfAlias) SetType(v string) {
	o.Type = v
}

// GetUrl returns the Url field value
func (o *ResponseIfAlias) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ResponseIfAlias) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ResponseIfAlias) SetUrl(v string) {
	o.Url = v
}

func (o ResponseIfAlias) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseIfAlias) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AliasedTo) {
		toSerialize["aliasedTo"] = o.AliasedTo
	}
	if !IsNil(o.ExternalSource) {
		toSerialize["externalSource"] = o.ExternalSource
	}
	if !IsNil(o.ExternalSourceType) {
		toSerialize["externalSourceType"] = o.ExternalSourceType
	}
	if !IsNil(o.PreserveExternalPath) {
		toSerialize["preserveExternalPath"] = o.PreserveExternalPath
	}
	if !IsNil(o.Redirect) {
		toSerialize["redirect"] = o.Redirect
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["type"] = o.Type
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ResponseIfAlias) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseIfAlias := _ResponseIfAlias{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseIfAlias)

	if err != nil {
		return err
	}

	*o = ResponseIfAlias(varResponseIfAlias)

	return err
}

type NullableResponseIfAlias struct {
	value *ResponseIfAlias
	isSet bool
}

func (v NullableResponseIfAlias) Get() *ResponseIfAlias {
	return v.value
}

func (v *NullableResponseIfAlias) Set(val *ResponseIfAlias) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseIfAlias) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseIfAlias) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseIfAlias(val *ResponseIfAlias) *NullableResponseIfAlias {
	return &NullableResponseIfAlias{value: val, isSet: true}
}

func (v NullableResponseIfAlias) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseIfAlias) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


