/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeploymentCreateInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentCreateInputBody{}

// DeploymentCreateInputBody struct for DeploymentCreateInputBody
type DeploymentCreateInputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	ExternalSource *string `json:"externalSource,omitempty"`
	ExternalSourceType *string `json:"externalSourceType,omitempty"`
	Name *string `json:"name,omitempty"`
	PreserveExternalPath *bool `json:"preserveExternalPath,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Urls []Url `json:"urls"`
}

type _DeploymentCreateInputBody DeploymentCreateInputBody

// NewDeploymentCreateInputBody instantiates a new DeploymentCreateInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentCreateInputBody(urls []Url) *DeploymentCreateInputBody {
	this := DeploymentCreateInputBody{}
	this.Urls = urls
	return &this
}

// NewDeploymentCreateInputBodyWithDefaults instantiates a new DeploymentCreateInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentCreateInputBodyWithDefaults() *DeploymentCreateInputBody {
	this := DeploymentCreateInputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *DeploymentCreateInputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCreateInputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *DeploymentCreateInputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *DeploymentCreateInputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetExternalSource returns the ExternalSource field value if set, zero value otherwise.
func (o *DeploymentCreateInputBody) GetExternalSource() string {
	if o == nil || IsNil(o.ExternalSource) {
		var ret string
		return ret
	}
	return *o.ExternalSource
}

// GetExternalSourceOk returns a tuple with the ExternalSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCreateInputBody) GetExternalSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSource) {
		return nil, false
	}
	return o.ExternalSource, true
}

// HasExternalSource returns a boolean if a field has been set.
func (o *DeploymentCreateInputBody) HasExternalSource() bool {
	if o != nil && !IsNil(o.ExternalSource) {
		return true
	}

	return false
}

// SetExternalSource gets a reference to the given string and assigns it to the ExternalSource field.
func (o *DeploymentCreateInputBody) SetExternalSource(v string) {
	o.ExternalSource = &v
}

// GetExternalSourceType returns the ExternalSourceType field value if set, zero value otherwise.
func (o *DeploymentCreateInputBody) GetExternalSourceType() string {
	if o == nil || IsNil(o.ExternalSourceType) {
		var ret string
		return ret
	}
	return *o.ExternalSourceType
}

// GetExternalSourceTypeOk returns a tuple with the ExternalSourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCreateInputBody) GetExternalSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSourceType) {
		return nil, false
	}
	return o.ExternalSourceType, true
}

// HasExternalSourceType returns a boolean if a field has been set.
func (o *DeploymentCreateInputBody) HasExternalSourceType() bool {
	if o != nil && !IsNil(o.ExternalSourceType) {
		return true
	}

	return false
}

// SetExternalSourceType gets a reference to the given string and assigns it to the ExternalSourceType field.
func (o *DeploymentCreateInputBody) SetExternalSourceType(v string) {
	o.ExternalSourceType = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeploymentCreateInputBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCreateInputBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeploymentCreateInputBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeploymentCreateInputBody) SetName(v string) {
	o.Name = &v
}

// GetPreserveExternalPath returns the PreserveExternalPath field value if set, zero value otherwise.
func (o *DeploymentCreateInputBody) GetPreserveExternalPath() bool {
	if o == nil || IsNil(o.PreserveExternalPath) {
		var ret bool
		return ret
	}
	return *o.PreserveExternalPath
}

// GetPreserveExternalPathOk returns a tuple with the PreserveExternalPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCreateInputBody) GetPreserveExternalPathOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveExternalPath) {
		return nil, false
	}
	return o.PreserveExternalPath, true
}

// HasPreserveExternalPath returns a boolean if a field has been set.
func (o *DeploymentCreateInputBody) HasPreserveExternalPath() bool {
	if o != nil && !IsNil(o.PreserveExternalPath) {
		return true
	}

	return false
}

// SetPreserveExternalPath gets a reference to the given bool and assigns it to the PreserveExternalPath field.
func (o *DeploymentCreateInputBody) SetPreserveExternalPath(v bool) {
	o.PreserveExternalPath = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeploymentCreateInputBody) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentCreateInputBody) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *DeploymentCreateInputBody) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *DeploymentCreateInputBody) SetTags(v []string) {
	o.Tags = v
}

// GetUrls returns the Urls field value
// If the value is explicit nil, the zero value for []Url will be returned
func (o *DeploymentCreateInputBody) GetUrls() []Url {
	if o == nil {
		var ret []Url
		return ret
	}

	return o.Urls
}

// GetUrlsOk returns a tuple with the Urls field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentCreateInputBody) GetUrlsOk() ([]Url, bool) {
	if o == nil || IsNil(o.Urls) {
		return nil, false
	}
	return o.Urls, true
}

// SetUrls sets field value
func (o *DeploymentCreateInputBody) SetUrls(v []Url) {
	o.Urls = v
}

func (o DeploymentCreateInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentCreateInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if !IsNil(o.ExternalSource) {
		toSerialize["externalSource"] = o.ExternalSource
	}
	if !IsNil(o.ExternalSourceType) {
		toSerialize["externalSourceType"] = o.ExternalSourceType
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PreserveExternalPath) {
		toSerialize["preserveExternalPath"] = o.PreserveExternalPath
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Urls != nil {
		toSerialize["urls"] = o.Urls
	}
	return toSerialize, nil
}

func (o *DeploymentCreateInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"urls",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentCreateInputBody := _DeploymentCreateInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentCreateInputBody)

	if err != nil {
		return err
	}

	*o = DeploymentCreateInputBody(varDeploymentCreateInputBody)

	return err
}

type NullableDeploymentCreateInputBody struct {
	value *DeploymentCreateInputBody
	isSet bool
}

func (v NullableDeploymentCreateInputBody) Get() *DeploymentCreateInputBody {
	return v.value
}

func (v *NullableDeploymentCreateInputBody) Set(val *DeploymentCreateInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentCreateInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentCreateInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentCreateInputBody(val *DeploymentCreateInputBody) *NullableDeploymentCreateInputBody {
	return &NullableDeploymentCreateInputBody{value: val, isSet: true}
}

func (v NullableDeploymentCreateInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentCreateInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


