/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddExternalUserInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddExternalUserInputBody{}

// AddExternalUserInputBody struct for AddExternalUserInputBody
type AddExternalUserInputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	ExternalUserHandle *string `json:"externalUserHandle,omitempty"`
	ExternalUserId *string `json:"externalUserId,omitempty"`
	ExternalUserSource string `json:"externalUserSource"`
}

type _AddExternalUserInputBody AddExternalUserInputBody

// NewAddExternalUserInputBody instantiates a new AddExternalUserInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddExternalUserInputBody(externalUserSource string) *AddExternalUserInputBody {
	this := AddExternalUserInputBody{}
	this.ExternalUserSource = externalUserSource
	return &this
}

// NewAddExternalUserInputBodyWithDefaults instantiates a new AddExternalUserInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddExternalUserInputBodyWithDefaults() *AddExternalUserInputBody {
	this := AddExternalUserInputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *AddExternalUserInputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddExternalUserInputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *AddExternalUserInputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *AddExternalUserInputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetExternalUserHandle returns the ExternalUserHandle field value if set, zero value otherwise.
func (o *AddExternalUserInputBody) GetExternalUserHandle() string {
	if o == nil || IsNil(o.ExternalUserHandle) {
		var ret string
		return ret
	}
	return *o.ExternalUserHandle
}

// GetExternalUserHandleOk returns a tuple with the ExternalUserHandle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddExternalUserInputBody) GetExternalUserHandleOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalUserHandle) {
		return nil, false
	}
	return o.ExternalUserHandle, true
}

// HasExternalUserHandle returns a boolean if a field has been set.
func (o *AddExternalUserInputBody) HasExternalUserHandle() bool {
	if o != nil && !IsNil(o.ExternalUserHandle) {
		return true
	}

	return false
}

// SetExternalUserHandle gets a reference to the given string and assigns it to the ExternalUserHandle field.
func (o *AddExternalUserInputBody) SetExternalUserHandle(v string) {
	o.ExternalUserHandle = &v
}

// GetExternalUserId returns the ExternalUserId field value if set, zero value otherwise.
func (o *AddExternalUserInputBody) GetExternalUserId() string {
	if o == nil || IsNil(o.ExternalUserId) {
		var ret string
		return ret
	}
	return *o.ExternalUserId
}

// GetExternalUserIdOk returns a tuple with the ExternalUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddExternalUserInputBody) GetExternalUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalUserId) {
		return nil, false
	}
	return o.ExternalUserId, true
}

// HasExternalUserId returns a boolean if a field has been set.
func (o *AddExternalUserInputBody) HasExternalUserId() bool {
	if o != nil && !IsNil(o.ExternalUserId) {
		return true
	}

	return false
}

// SetExternalUserId gets a reference to the given string and assigns it to the ExternalUserId field.
func (o *AddExternalUserInputBody) SetExternalUserId(v string) {
	o.ExternalUserId = &v
}

// GetExternalUserSource returns the ExternalUserSource field value
func (o *AddExternalUserInputBody) GetExternalUserSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalUserSource
}

// GetExternalUserSourceOk returns a tuple with the ExternalUserSource field value
// and a boolean to check if the value has been set.
func (o *AddExternalUserInputBody) GetExternalUserSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalUserSource, true
}

// SetExternalUserSource sets field value
func (o *AddExternalUserInputBody) SetExternalUserSource(v string) {
	o.ExternalUserSource = v
}

func (o AddExternalUserInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddExternalUserInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if !IsNil(o.ExternalUserHandle) {
		toSerialize["externalUserHandle"] = o.ExternalUserHandle
	}
	if !IsNil(o.ExternalUserId) {
		toSerialize["externalUserId"] = o.ExternalUserId
	}
	toSerialize["externalUserSource"] = o.ExternalUserSource
	return toSerialize, nil
}

func (o *AddExternalUserInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"externalUserSource",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddExternalUserInputBody := _AddExternalUserInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddExternalUserInputBody)

	if err != nil {
		return err
	}

	*o = AddExternalUserInputBody(varAddExternalUserInputBody)

	return err
}

type NullableAddExternalUserInputBody struct {
	value *AddExternalUserInputBody
	isSet bool
}

func (v NullableAddExternalUserInputBody) Get() *AddExternalUserInputBody {
	return v.value
}

func (v *NullableAddExternalUserInputBody) Set(val *AddExternalUserInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAddExternalUserInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAddExternalUserInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddExternalUserInputBody(val *AddExternalUserInputBody) *NullableAddExternalUserInputBody {
	return &NullableAddExternalUserInputBody{value: val, isSet: true}
}

func (v NullableAddExternalUserInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddExternalUserInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


