/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HealthCheckOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthCheckOutputBody{}

// HealthCheckOutputBody struct for HealthCheckOutputBody
type HealthCheckOutputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Ok bool `json:"ok"`
}

type _HealthCheckOutputBody HealthCheckOutputBody

// NewHealthCheckOutputBody instantiates a new HealthCheckOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthCheckOutputBody(ok bool) *HealthCheckOutputBody {
	this := HealthCheckOutputBody{}
	this.Ok = ok
	return &this
}

// NewHealthCheckOutputBodyWithDefaults instantiates a new HealthCheckOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthCheckOutputBodyWithDefaults() *HealthCheckOutputBody {
	this := HealthCheckOutputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *HealthCheckOutputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthCheckOutputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *HealthCheckOutputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *HealthCheckOutputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetOk returns the Ok field value
func (o *HealthCheckOutputBody) GetOk() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ok
}

// GetOkOk returns a tuple with the Ok field value
// and a boolean to check if the value has been set.
func (o *HealthCheckOutputBody) GetOkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ok, true
}

// SetOk sets field value
func (o *HealthCheckOutputBody) SetOk(v bool) {
	o.Ok = v
}

func (o HealthCheckOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthCheckOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["ok"] = o.Ok
	return toSerialize, nil
}

func (o *HealthCheckOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ok",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthCheckOutputBody := _HealthCheckOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHealthCheckOutputBody)

	if err != nil {
		return err
	}

	*o = HealthCheckOutputBody(varHealthCheckOutputBody)

	return err
}

type NullableHealthCheckOutputBody struct {
	value *HealthCheckOutputBody
	isSet bool
}

func (v NullableHealthCheckOutputBody) Get() *HealthCheckOutputBody {
	return v.value
}

func (v *NullableHealthCheckOutputBody) Set(val *HealthCheckOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthCheckOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthCheckOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthCheckOutputBody(val *HealthCheckOutputBody) *NullableHealthCheckOutputBody {
	return &NullableHealthCheckOutputBody{value: val, isSet: true}
}

func (v NullableHealthCheckOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthCheckOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


