/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmptyDeployment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmptyDeployment{}

// EmptyDeployment struct for EmptyDeployment
type EmptyDeployment struct {
	// Original repository for this deployment's source. Can include a branch name.
	ExternalSource *string `json:"externalSource,omitempty"`
	// Place where the original repository lives.
	ExternalSourceType *string `json:"externalSourceType,omitempty"`
	// Set to true to indicate that this deployment has not yet been set up.
	NoContentYet bool `json:"noContentYet"`
	// if this is true and the deployment url has a path like \"/thing\", then the \"/thing\" in the path will be transparently passed through to the underlying resource instead of being removed (which is the default)
	PreserveExternalPath *bool `json:"preserveExternalPath,omitempty"`
	// Tags used for metadata.
	Tags []string `json:"tags,omitempty"`
	// Type of deployment contents.
	Type string `json:"type"`
	// URL that this deployment will appear at. The DNS for the domain has to be set up first.
	Url string `json:"url"`
}

type _EmptyDeployment EmptyDeployment

// NewEmptyDeployment instantiates a new EmptyDeployment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmptyDeployment(noContentYet bool, type_ string, url string) *EmptyDeployment {
	this := EmptyDeployment{}
	this.NoContentYet = noContentYet
	this.Type = type_
	this.Url = url
	return &this
}

// NewEmptyDeploymentWithDefaults instantiates a new EmptyDeployment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmptyDeploymentWithDefaults() *EmptyDeployment {
	this := EmptyDeployment{}
	return &this
}

// GetExternalSource returns the ExternalSource field value if set, zero value otherwise.
func (o *EmptyDeployment) GetExternalSource() string {
	if o == nil || IsNil(o.ExternalSource) {
		var ret string
		return ret
	}
	return *o.ExternalSource
}

// GetExternalSourceOk returns a tuple with the ExternalSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmptyDeployment) GetExternalSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSource) {
		return nil, false
	}
	return o.ExternalSource, true
}

// HasExternalSource returns a boolean if a field has been set.
func (o *EmptyDeployment) HasExternalSource() bool {
	if o != nil && !IsNil(o.ExternalSource) {
		return true
	}

	return false
}

// SetExternalSource gets a reference to the given string and assigns it to the ExternalSource field.
func (o *EmptyDeployment) SetExternalSource(v string) {
	o.ExternalSource = &v
}

// GetExternalSourceType returns the ExternalSourceType field value if set, zero value otherwise.
func (o *EmptyDeployment) GetExternalSourceType() string {
	if o == nil || IsNil(o.ExternalSourceType) {
		var ret string
		return ret
	}
	return *o.ExternalSourceType
}

// GetExternalSourceTypeOk returns a tuple with the ExternalSourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmptyDeployment) GetExternalSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSourceType) {
		return nil, false
	}
	return o.ExternalSourceType, true
}

// HasExternalSourceType returns a boolean if a field has been set.
func (o *EmptyDeployment) HasExternalSourceType() bool {
	if o != nil && !IsNil(o.ExternalSourceType) {
		return true
	}

	return false
}

// SetExternalSourceType gets a reference to the given string and assigns it to the ExternalSourceType field.
func (o *EmptyDeployment) SetExternalSourceType(v string) {
	o.ExternalSourceType = &v
}

// GetNoContentYet returns the NoContentYet field value
func (o *EmptyDeployment) GetNoContentYet() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.NoContentYet
}

// GetNoContentYetOk returns a tuple with the NoContentYet field value
// and a boolean to check if the value has been set.
func (o *EmptyDeployment) GetNoContentYetOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NoContentYet, true
}

// SetNoContentYet sets field value
func (o *EmptyDeployment) SetNoContentYet(v bool) {
	o.NoContentYet = v
}

// GetPreserveExternalPath returns the PreserveExternalPath field value if set, zero value otherwise.
func (o *EmptyDeployment) GetPreserveExternalPath() bool {
	if o == nil || IsNil(o.PreserveExternalPath) {
		var ret bool
		return ret
	}
	return *o.PreserveExternalPath
}

// GetPreserveExternalPathOk returns a tuple with the PreserveExternalPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmptyDeployment) GetPreserveExternalPathOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveExternalPath) {
		return nil, false
	}
	return o.PreserveExternalPath, true
}

// HasPreserveExternalPath returns a boolean if a field has been set.
func (o *EmptyDeployment) HasPreserveExternalPath() bool {
	if o != nil && !IsNil(o.PreserveExternalPath) {
		return true
	}

	return false
}

// SetPreserveExternalPath gets a reference to the given bool and assigns it to the PreserveExternalPath field.
func (o *EmptyDeployment) SetPreserveExternalPath(v bool) {
	o.PreserveExternalPath = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmptyDeployment) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmptyDeployment) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *EmptyDeployment) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *EmptyDeployment) SetTags(v []string) {
	o.Tags = v
}

// GetType returns the Type field value
func (o *EmptyDeployment) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EmptyDeployment) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EmptyDeployment) SetType(v string) {
	o.Type = v
}

// GetUrl returns the Url field value
func (o *EmptyDeployment) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *EmptyDeployment) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *EmptyDeployment) SetUrl(v string) {
	o.Url = v
}

func (o EmptyDeployment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmptyDeployment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalSource) {
		toSerialize["externalSource"] = o.ExternalSource
	}
	if !IsNil(o.ExternalSourceType) {
		toSerialize["externalSourceType"] = o.ExternalSourceType
	}
	toSerialize["noContentYet"] = o.NoContentYet
	if !IsNil(o.PreserveExternalPath) {
		toSerialize["preserveExternalPath"] = o.PreserveExternalPath
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["type"] = o.Type
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *EmptyDeployment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"noContentYet",
		"type",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmptyDeployment := _EmptyDeployment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmptyDeployment)

	if err != nil {
		return err
	}

	*o = EmptyDeployment(varEmptyDeployment)

	return err
}

type NullableEmptyDeployment struct {
	value *EmptyDeployment
	isSet bool
}

func (v NullableEmptyDeployment) Get() *EmptyDeployment {
	return v.value
}

func (v *NullableEmptyDeployment) Set(val *EmptyDeployment) {
	v.value = val
	v.isSet = true
}

func (v NullableEmptyDeployment) IsSet() bool {
	return v.isSet
}

func (v *NullableEmptyDeployment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmptyDeployment(val *EmptyDeployment) *NullableEmptyDeployment {
	return &NullableEmptyDeployment{value: val, isSet: true}
}

func (v NullableEmptyDeployment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmptyDeployment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


