/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuccessOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessOutputBody{}

// SuccessOutputBody struct for SuccessOutputBody
type SuccessOutputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Message string `json:"message"`
	Success bool `json:"success"`
}

type _SuccessOutputBody SuccessOutputBody

// NewSuccessOutputBody instantiates a new SuccessOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessOutputBody(message string, success bool) *SuccessOutputBody {
	this := SuccessOutputBody{}
	this.Message = message
	this.Success = success
	return &this
}

// NewSuccessOutputBodyWithDefaults instantiates a new SuccessOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessOutputBodyWithDefaults() *SuccessOutputBody {
	this := SuccessOutputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *SuccessOutputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessOutputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *SuccessOutputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *SuccessOutputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetMessage returns the Message field value
func (o *SuccessOutputBody) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SuccessOutputBody) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SuccessOutputBody) SetMessage(v string) {
	o.Message = v
}

// GetSuccess returns the Success field value
func (o *SuccessOutputBody) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *SuccessOutputBody) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *SuccessOutputBody) SetSuccess(v bool) {
	o.Success = v
}

func (o SuccessOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["message"] = o.Message
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *SuccessOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessOutputBody := _SuccessOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuccessOutputBody)

	if err != nil {
		return err
	}

	*o = SuccessOutputBody(varSuccessOutputBody)

	return err
}

type NullableSuccessOutputBody struct {
	value *SuccessOutputBody
	isSet bool
}

func (v NullableSuccessOutputBody) Get() *SuccessOutputBody {
	return v.value
}

func (v *NullableSuccessOutputBody) Set(val *SuccessOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessOutputBody(val *SuccessOutputBody) *NullableSuccessOutputBody {
	return &NullableSuccessOutputBody{value: val, isSet: true}
}

func (v NullableSuccessOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


