/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeployAliasBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeployAliasBody{}

// DeployAliasBody struct for DeployAliasBody
type DeployAliasBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// The URL of the deployment that you're updating.
	Url string `json:"Url"`
	// The URL that this deployment is an alias for.
	AliasedTo *string `json:"aliasedTo,omitempty"`
	// If this is true, visitors to this deployment's URL will be completely redirected to the URL that this alias is for.
	Redirect *bool `json:"redirect,omitempty"`
}

type _DeployAliasBody DeployAliasBody

// NewDeployAliasBody instantiates a new DeployAliasBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeployAliasBody(url string) *DeployAliasBody {
	this := DeployAliasBody{}
	this.Url = url
	return &this
}

// NewDeployAliasBodyWithDefaults instantiates a new DeployAliasBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeployAliasBodyWithDefaults() *DeployAliasBody {
	this := DeployAliasBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *DeployAliasBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAliasBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *DeployAliasBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *DeployAliasBody) SetSchema(v string) {
	o.Schema = &v
}

// GetUrl returns the Url field value
func (o *DeployAliasBody) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *DeployAliasBody) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *DeployAliasBody) SetUrl(v string) {
	o.Url = v
}

// GetAliasedTo returns the AliasedTo field value if set, zero value otherwise.
func (o *DeployAliasBody) GetAliasedTo() string {
	if o == nil || IsNil(o.AliasedTo) {
		var ret string
		return ret
	}
	return *o.AliasedTo
}

// GetAliasedToOk returns a tuple with the AliasedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAliasBody) GetAliasedToOk() (*string, bool) {
	if o == nil || IsNil(o.AliasedTo) {
		return nil, false
	}
	return o.AliasedTo, true
}

// HasAliasedTo returns a boolean if a field has been set.
func (o *DeployAliasBody) HasAliasedTo() bool {
	if o != nil && !IsNil(o.AliasedTo) {
		return true
	}

	return false
}

// SetAliasedTo gets a reference to the given string and assigns it to the AliasedTo field.
func (o *DeployAliasBody) SetAliasedTo(v string) {
	o.AliasedTo = &v
}

// GetRedirect returns the Redirect field value if set, zero value otherwise.
func (o *DeployAliasBody) GetRedirect() bool {
	if o == nil || IsNil(o.Redirect) {
		var ret bool
		return ret
	}
	return *o.Redirect
}

// GetRedirectOk returns a tuple with the Redirect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAliasBody) GetRedirectOk() (*bool, bool) {
	if o == nil || IsNil(o.Redirect) {
		return nil, false
	}
	return o.Redirect, true
}

// HasRedirect returns a boolean if a field has been set.
func (o *DeployAliasBody) HasRedirect() bool {
	if o != nil && !IsNil(o.Redirect) {
		return true
	}

	return false
}

// SetRedirect gets a reference to the given bool and assigns it to the Redirect field.
func (o *DeployAliasBody) SetRedirect(v bool) {
	o.Redirect = &v
}

func (o DeployAliasBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeployAliasBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["Url"] = o.Url
	if !IsNil(o.AliasedTo) {
		toSerialize["aliasedTo"] = o.AliasedTo
	}
	if !IsNil(o.Redirect) {
		toSerialize["redirect"] = o.Redirect
	}
	return toSerialize, nil
}

func (o *DeployAliasBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeployAliasBody := _DeployAliasBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeployAliasBody)

	if err != nil {
		return err
	}

	*o = DeployAliasBody(varDeployAliasBody)

	return err
}

type NullableDeployAliasBody struct {
	value *DeployAliasBody
	isSet bool
}

func (v NullableDeployAliasBody) Get() *DeployAliasBody {
	return v.value
}

func (v *NullableDeployAliasBody) Set(val *DeployAliasBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDeployAliasBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDeployAliasBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeployAliasBody(val *DeployAliasBody) *NullableDeployAliasBody {
	return &NullableDeployAliasBody{value: val, isSet: true}
}

func (v NullableDeployAliasBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeployAliasBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


