/*
Internet Golf API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package golfsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseIfStaticSite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseIfStaticSite{}

// ResponseIfStaticSite struct for ResponseIfStaticSite
type ResponseIfStaticSite struct {
	// Original repository for this deployment's source. Can include a branch name.
	ExternalSource *string `json:"externalSource,omitempty"`
	// Place where the original repository lives.
	ExternalSourceType *string `json:"externalSourceType,omitempty"`
	// if this is true and the deployment url has a path like \"/thing\", then the \"/thing\" in the path will be transparently passed through to the underlying resource instead of being removed (which is the default)
	PreserveExternalPath *bool `json:"preserveExternalPath,omitempty"`
	// The path to this deployment's files on the server.
	ServerContentLocation *string `json:"serverContentLocation,omitempty"`
	// Whether this deployment is set up to support a Single Page App by using /index.html as a fallback for all requests.
	SpaMode *bool `json:"spaMode,omitempty"`
	// Tags used for metadata.
	Tags []string `json:"tags,omitempty"`
	// Type of deployment contents.
	Type string `json:"type"`
	// URL that this deployment will appear at. The DNS for the domain has to be set up first.
	Url string `json:"url"`
}

type _ResponseIfStaticSite ResponseIfStaticSite

// NewResponseIfStaticSite instantiates a new ResponseIfStaticSite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseIfStaticSite(type_ string, url string) *ResponseIfStaticSite {
	this := ResponseIfStaticSite{}
	this.Type = type_
	this.Url = url
	return &this
}

// NewResponseIfStaticSiteWithDefaults instantiates a new ResponseIfStaticSite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseIfStaticSiteWithDefaults() *ResponseIfStaticSite {
	this := ResponseIfStaticSite{}
	return &this
}

// GetExternalSource returns the ExternalSource field value if set, zero value otherwise.
func (o *ResponseIfStaticSite) GetExternalSource() string {
	if o == nil || IsNil(o.ExternalSource) {
		var ret string
		return ret
	}
	return *o.ExternalSource
}

// GetExternalSourceOk returns a tuple with the ExternalSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIfStaticSite) GetExternalSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSource) {
		return nil, false
	}
	return o.ExternalSource, true
}

// HasExternalSource returns a boolean if a field has been set.
func (o *ResponseIfStaticSite) HasExternalSource() bool {
	if o != nil && !IsNil(o.ExternalSource) {
		return true
	}

	return false
}

// SetExternalSource gets a reference to the given string and assigns it to the ExternalSource field.
func (o *ResponseIfStaticSite) SetExternalSource(v string) {
	o.ExternalSource = &v
}

// GetExternalSourceType returns the ExternalSourceType field value if set, zero value otherwise.
func (o *ResponseIfStaticSite) GetExternalSourceType() string {
	if o == nil || IsNil(o.ExternalSourceType) {
		var ret string
		return ret
	}
	return *o.ExternalSourceType
}

// GetExternalSourceTypeOk returns a tuple with the ExternalSourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIfStaticSite) GetExternalSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSourceType) {
		return nil, false
	}
	return o.ExternalSourceType, true
}

// HasExternalSourceType returns a boolean if a field has been set.
func (o *ResponseIfStaticSite) HasExternalSourceType() bool {
	if o != nil && !IsNil(o.ExternalSourceType) {
		return true
	}

	return false
}

// SetExternalSourceType gets a reference to the given string and assigns it to the ExternalSourceType field.
func (o *ResponseIfStaticSite) SetExternalSourceType(v string) {
	o.ExternalSourceType = &v
}

// GetPreserveExternalPath returns the PreserveExternalPath field value if set, zero value otherwise.
func (o *ResponseIfStaticSite) GetPreserveExternalPath() bool {
	if o == nil || IsNil(o.PreserveExternalPath) {
		var ret bool
		return ret
	}
	return *o.PreserveExternalPath
}

// GetPreserveExternalPathOk returns a tuple with the PreserveExternalPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIfStaticSite) GetPreserveExternalPathOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveExternalPath) {
		return nil, false
	}
	return o.PreserveExternalPath, true
}

// HasPreserveExternalPath returns a boolean if a field has been set.
func (o *ResponseIfStaticSite) HasPreserveExternalPath() bool {
	if o != nil && !IsNil(o.PreserveExternalPath) {
		return true
	}

	return false
}

// SetPreserveExternalPath gets a reference to the given bool and assigns it to the PreserveExternalPath field.
func (o *ResponseIfStaticSite) SetPreserveExternalPath(v bool) {
	o.PreserveExternalPath = &v
}

// GetServerContentLocation returns the ServerContentLocation field value if set, zero value otherwise.
func (o *ResponseIfStaticSite) GetServerContentLocation() string {
	if o == nil || IsNil(o.ServerContentLocation) {
		var ret string
		return ret
	}
	return *o.ServerContentLocation
}

// GetServerContentLocationOk returns a tuple with the ServerContentLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIfStaticSite) GetServerContentLocationOk() (*string, bool) {
	if o == nil || IsNil(o.ServerContentLocation) {
		return nil, false
	}
	return o.ServerContentLocation, true
}

// HasServerContentLocation returns a boolean if a field has been set.
func (o *ResponseIfStaticSite) HasServerContentLocation() bool {
	if o != nil && !IsNil(o.ServerContentLocation) {
		return true
	}

	return false
}

// SetServerContentLocation gets a reference to the given string and assigns it to the ServerContentLocation field.
func (o *ResponseIfStaticSite) SetServerContentLocation(v string) {
	o.ServerContentLocation = &v
}

// GetSpaMode returns the SpaMode field value if set, zero value otherwise.
func (o *ResponseIfStaticSite) GetSpaMode() bool {
	if o == nil || IsNil(o.SpaMode) {
		var ret bool
		return ret
	}
	return *o.SpaMode
}

// GetSpaModeOk returns a tuple with the SpaMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIfStaticSite) GetSpaModeOk() (*bool, bool) {
	if o == nil || IsNil(o.SpaMode) {
		return nil, false
	}
	return o.SpaMode, true
}

// HasSpaMode returns a boolean if a field has been set.
func (o *ResponseIfStaticSite) HasSpaMode() bool {
	if o != nil && !IsNil(o.SpaMode) {
		return true
	}

	return false
}

// SetSpaMode gets a reference to the given bool and assigns it to the SpaMode field.
func (o *ResponseIfStaticSite) SetSpaMode(v bool) {
	o.SpaMode = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseIfStaticSite) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseIfStaticSite) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ResponseIfStaticSite) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *ResponseIfStaticSite) SetTags(v []string) {
	o.Tags = v
}

// GetType returns the Type field value
func (o *ResponseIfStaticSite) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ResponseIfStaticSite) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ResponseIfStaticSite) SetType(v string) {
	o.Type = v
}

// GetUrl returns the Url field value
func (o *ResponseIfStaticSite) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ResponseIfStaticSite) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ResponseIfStaticSite) SetUrl(v string) {
	o.Url = v
}

func (o ResponseIfStaticSite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseIfStaticSite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalSource) {
		toSerialize["externalSource"] = o.ExternalSource
	}
	if !IsNil(o.ExternalSourceType) {
		toSerialize["externalSourceType"] = o.ExternalSourceType
	}
	if !IsNil(o.PreserveExternalPath) {
		toSerialize["preserveExternalPath"] = o.PreserveExternalPath
	}
	if !IsNil(o.ServerContentLocation) {
		toSerialize["serverContentLocation"] = o.ServerContentLocation
	}
	if !IsNil(o.SpaMode) {
		toSerialize["spaMode"] = o.SpaMode
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["type"] = o.Type
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ResponseIfStaticSite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseIfStaticSite := _ResponseIfStaticSite{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseIfStaticSite)

	if err != nil {
		return err
	}

	*o = ResponseIfStaticSite(varResponseIfStaticSite)

	return err
}

type NullableResponseIfStaticSite struct {
	value *ResponseIfStaticSite
	isSet bool
}

func (v NullableResponseIfStaticSite) Get() *ResponseIfStaticSite {
	return v.value
}

func (v *NullableResponseIfStaticSite) Set(val *ResponseIfStaticSite) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseIfStaticSite) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseIfStaticSite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseIfStaticSite(val *ResponseIfStaticSite) *NullableResponseIfStaticSite {
	return &NullableResponseIfStaticSite{value: val, isSet: true}
}

func (v NullableResponseIfStaticSite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseIfStaticSite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


