name: Deploy Official Site

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: internet-golf/deploy@v0.0.4
      - run: |
          golf deploy-content internetgolf.stuffedanimal.family --auth github-oidc --files ./official-website
