name: Deploy Official Site

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: toBeOfUse/internet-golf/.github/actions@v0.1.3
      - run: |
          golf deploy-content internetgolf.stuffedanimal.family --auth github-oidc --files ./official-website
