name: Build and Release Go Project

permissions:
  contents: write

on:
  push:
    tags:
      - "v*" # Trigger on new tags starting with 'v' (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          # TODO: can this just come from go.mod
          go-version: "1.25"

      - name: Build binaries
        # can these builds be parallelized? would that even matter?
        run: |
          GOOS=linux GOARCH=amd64 go build -o golf-server-linux-amd64 ./cmd
          GOOS=windows GOARCH=amd64 go build -o golf-server-windows-amd64.exe ./cmd
          GOOS=linux GOARCH=amd64 go build -o golf-linux-amd64 ./client-cmd
          GOOS=windows GOARCH=amd64 go build -o golf-windows-amd64.exe ./client-cmd

      - name: Create Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }}" \
            golf-server-linux-amd64 \
            golf-server-windows-amd64.exe \
            golf-linux-amd64 \
            golf-windows-amd64.exe
