name: Build and Release Go Project

permissions:
  contents: write

on:
  push:
    tags:
      - "v*" # Trigger on new tags starting with 'v' (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: windows
            goarch: amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build binaries
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o golf-server-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} ./cmd
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o golf-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} ./client-cmd

      - name: Create archive
        run: |
          if [ "${{ matrix.goos }}" == "linux" ]; then
            tar -czf golf-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz golf-server-${{ matrix.goos }}-${{ matrix.goarch }} golf-${{ matrix.goos }}-${{ matrix.goarch }}
          else
            zip golf-${{ matrix.goos }}-${{ matrix.goarch }}.zip golf-server-${{ matrix.goos }}-${{ matrix.goarch }}.exe golf-${{ matrix.goos }}-${{ matrix.goarch }}.exe
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: golf-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            golf-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
            golf-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }}" \
            artifacts/golf-linux-amd64/* \
            artifacts/golf-windows-amd64/*
